name: Checkout Actions
on: [push]
jobs:
  checkout-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files before
        run: ls -a
      - uses: actions/chrckout@v3
      - name: List files After
        run: ls -a
