name: First Workflow
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure workflow
        run: echo "Hello World"
      - name: Multiple Command
        run: |
          node -v
          npm -v
