name: Martrix
on: [push]
jobs:
  node-matrix:
    continue-on-error: false #To prevent workflow from failing, if a jobs has failed
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14, 15, 16]
      fail-fast: false #If any job fails the other are going to continue normally
      # max-parallel: 3 #Only max 3 job will be run at the same time
    runs-on: ${{ matrix.os }}
    steps:
    - run: node -v
    - uses: actions/setup-node@v3
      with:
        node-versions: ${{ matrix.node-version }}
    - run: node -v