name: Status Check Functions
on: [push]
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Step 2
        run: exit 1
      - name: Runs on Failure
        if: failure() && steps.steps-2.conclusion == 'failure'
        run: echo "Run only on failure"
      - name: Runs on Success
        if: success()
        run: echo "Run only on success"
      - name: Always Run
        if: always()
        run: echo "Run only on always"
    job-2:
      runs-on: ubuntu-latest
      needs: job-1
      if: failure()


          
